// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stack from "./Stack.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function 001(props) {
  return JsxRuntime.jsxs(Stack.make, {
              children: [
                JsxRuntime.jsx("div", {}),
                JsxRuntime.jsx("div", {})
              ]
            });
}

var make = 001;

export {
  make ,
}
/* Stack Not a pure module */
