// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AsyncData from "./AsyncData.bs.mjs";

expect(AsyncData.loading(undefined)).toStrictEqual(/* Loading */1);

export {
  
}
/*  Not a pure module */
