// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AsyncData from "./AsyncData.bs.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.mjs";

var asyncData = Core__Option.map(/* NotAsked */0, AsyncData.toBusy);

export {
  asyncData ,
}
/* asyncData Not a pure module */
