// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "@testing-library/react";

React.screen.queryByRole("banner", {
      name: "banner"
    });

export {
  
}
/*  Not a pure module */
