// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Stack(props) {
  return JsxRuntime.jsx("div", {
              children: props.children
            });
}

var make = Stack;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
