// Generated by ReScript, PLEASE EDIT WITH CARE


function DomElement_blur(prim) {
  prim.blur();
}

function DomElement_offsetWidth(prim) {
  return prim.offsetWidth;
}

function DomElement_offsetHeight(prim) {
  return prim.offsetHeight;
}

var DomElement = {
  blur: DomElement_blur,
  offsetWidth: DomElement_offsetWidth,
  offsetHeight: DomElement_offsetHeight
};

export {
  DomElement ,
}
/* No side effect */
